### ISSUE TITLE
Lij increasing linearly 

### ISSUE THREAD

**Issue by Jeamsanderson** [kdfong/transport-coefficients#1]
Hello, I am using this program to calculate the conductivity of my system. I have prepared dump files for the velocity of cation and anion accordingly. While I am trying to implement this code, It looks like my Lij value is increasing linearly over time, although the raw velocity value is not increasing linearly with time. I have checked the systems is well equilibrated, then what makes this linear increment? Anyways, I used the real units in LAMMPS, what is the unit used in the example files? 

Thanks!

**Comment by kdfong** [comment]
The most likely cause of this issue is that you need more data to improve the statistics of the calculation. I would suggest (1) running your simulation longer and (2) averaging over multiple independent replicates of the same system. You might also try computing the transport coefficients based on the particle positions, rather than velocities, using the code here: https://github.com/kdfong/transport-coefficients-MSD. If none of these helps, please provide some more details about the system you are simulating. 

The data in the example files uses real units.
